### ISSUE TITLE
[Ask] Is it necessary to use php 7.1 as minimum requirement?

### ISSUE THREAD

**Issue by didikz** [GitScrum-Community/laravel-gitscrum#246]
in latest `composer.json` it is set php 7.1 as minimum requirement. Is it necessary? i think it is better to stick with laravel minimum requirement itself to use php 5.6 so we can reach more user to able install it.

**Comment by renatomarinho** [comment]
Hi @didikz 

Laravel 5.5 will be mandatory php7. I think it's interesting to prepare GitScrum for this update and to increase the perfomance.
https://laravel-news.com/laravel-5-5-php-7-0

I will use features of php7, example return types, null coalesce and others

What's you think about it?

**Comment by didikz** [comment]
I see, so you are planning to upgrade. But i think we need to keep minimum requirement since this is still using 5.4 until the next release comes up.

**Comment by renatomarinho** [comment]
@didikz  I did rollback to 5.6 version
