### ISSUE TITLE
(bug) Dragging issues between columns in the board planning view does not update issue state

### ISSUE THREAD

**Issue by StickNitro** [gitscrum-community/laravel-gitscrum#318]
## Detailed description

When dragging an issue between columns on the Board Planning view the issue state does not seem to update on the issue, for example:

Dragging an issue from `Todo` to `In Progress` updates the board but the issue state is still set to `Todo`.  When you refresh the board or open an issue the board updates and the issue jumps back to the `Todo` column

**Comment by renatomarinho** [comment]
This issue has been solved. Thank you for your help!
