### ISSUE TITLE
repositories not loaded

### ISSUE THREAD

**Issue by endytc** [gitscrum-community/laravel-gitscrum#329]
I have grant **api** and **read_user** of my gitlab account, but my repositories not loaded
![image](https://user-images.githubusercontent.com/1209684/44305536-15c50e80-a3a4-11e8-9aeb-5f3765d872c2.png)

**Comment by AgusRdz** [comment]
This is a confirmed issue and was fixed in this [PR](https://github.com/gitscrum-community/laravel-gitscrum/pull/330)
